### ISSUE TITLE
I do not understand the match strategy of you code?

### ISSUE THREAD

**Issue by davinca** [HiKapok/SSD.TensorFlow#1]
`between_mask = tf.logical_and(tf.less(match_values, high_thres), tf.greater_equal(match_values, low_thres)) ` 
`negative_mask = less_mask if ignore_between else between_mask ` 
`ignore_mask = between_mask if ignore_between else less_mask`

what does the ***between_mask*** means ? can u explain it more clearly?
Thanks you very much!

**Comment by HiKapok** [comment]
There are two strategies: 
1. negtives < low < ignore < high < positives, leave margin between positive and negtive makes it easier to learn, but maybe harmful.
2. ignore < low < negtives < high < positives, low overlap sampels are mostly very easier samples, so we can ignore them.

**Comment by davinca** [comment]
According to your instructions,I have configured the training environment. When i run *python train_ssd.py*, the errors occurred. I try to handle this issue but it doesn't work. I would be appreciate it if you help me solve the issue. here are the part of  information of errors:

![Uploading image.png…]()

**Comment by davinca** [comment]
@HiKapok .Thanks a lot!  According to your instructions, I have configured the training environment. When I run *python train_ssd.py*, errors occurred . I have tried to fix it, but it doesn't work. I would be  appreciated it if you could help me solve the issue. here are the part of information of the errors.

![selection_004](https://user-images.githubusercontent.com/22429939/39912493-7af415ce-5531-11e8-9fc2-5ade3c4276f8.png)

**Comment by HiKapok** [comment]
@davinca you should use the correct pre-trained model, to be clear, the pre-trained vgg model should be the reduced one,  get that [here](https://drive.google.com/drive/folders/184srhbt8_uvLKeWW_Yo8Mc5wTyc0lJT7) .
