### ISSUE TITLE
gpu fraction

### ISSUE THREAD

**Issue by zhengduoru** [HiKapok/SSD.TensorFlow#101]
I set FLAGS.gpu_memory_fraction=0.5 but it still occupied the whole gpu when training.
anyone meets this problem?

**Comment by HiKapok** [comment]
@zhengduoru set batch_size to 1 and try again?

**Comment by zhengduoru** [comment]
I tried to set batch_size to 1 , but nothing changes.

here is my config. Actually I only changed per_process_gpu_memory_fraction to 0.5

config: {'_save_checkpoints_secs': 7200, '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_global_id_in_cluster': 0, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fed99f69490>, '_model_dir': './logs/', '_protocol': None, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.5
}
allow_soft_placement: true
, '_tf_random_seed': 20180503, '_save_summary_steps': 500, '_device_fn': None, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 10, '_evaluation_master': '', '_eval_distribute': None, '_train_distribute': None, '_master': ''}

![image](https://user-images.githubusercontent.com/30524929/55696826-47511f80-59f1-11e9-9692-1808978e97c3.png)
