### ISSUE TITLE
questions about voc_eval.py

### ISSUE THREAD

**Issue by ydhongHIT** [HiKapok/SSD.TensorFlow#107]
I ran the program following the instruction but there was the problem.
VOC07 metric? Yes
Traceback (most recent call last):
  File "voc_eval.py", line 268, in <module>
    do_python_eval()
  File "voc_eval.py", line 79, in do_python_eval
    ovthresh=0.5, use_07_metric=use_07_metric)
  File "voc_eval.py", line 200, in voc_eval
    with open(detpath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './logs/predict/results_4.txt'
After this, I created files from 'results_1' to 'results_21' in the '/logs/predict' but it wasn't useful.

**Comment by zhouqinhe** [comment]
run **python eval_ssd.py** can build result_*.txt before **run python voc_eval.py**
