### ISSUE TITLE
About voc_eval.py

### ISSUE THREAD

**Issue by KevinWalkerFan** [HiKapok/SSD.TensorFlow#11]
I just finished training on my own dataset(10 classes) and Sucessfully run the eval_edsd.py. But an Error occurs when I run the voc_eval.py. It seems like there is something wrong with the VOC 07 11 point method.
![default](https://user-images.githubusercontent.com/26733530/41056829-f678a2fc-69f7-11e8-9ee0-01b72c8a2629.JPG)
![default](https://user-images.githubusercontent.com/26733530/41057089-b477e042-69f8-11e8-92ce-57902d223ab2.JPG)

**Comment by HiKapok** [comment]
voc_eval.py only can be used by VOC dataset, if you want to eval your own dataset, you need write a new one

**Comment by KevinWalkerFan** [comment]
Thank u. I just solve this problem. I make my own dataset VOC format and finished all the training and eval. I used the different  test dataset to do sad_eval and VOC_eval so it cannot match.

**Comment by Kasyene** [comment]
Hello @KevinWalkerFan maybe you're still here and can help me - I met with the same problem while training my own data.
My dataset is in VOC-like format but I still get the error. I'm using the same dataset for both eval_ssd.py and voc_ssd.py
Can you tell me if I missed something?
