### ISSUE TITLE
how to train my own data?

### ISSUE THREAD

**Issue by zcc720** [HiKapok/SSD.TensorFlow#12]
1.can this project train my own data?
2.if can,how to train?

**Comment by HiKapok** [comment]
Yes, of course. please follow dataset/convert_tfrecords.py to make your own *.tfrecords for your own dataset

**Comment by moonyoung430** [comment]
I want to train my own data too, and I already make my own *.tfrecords. But when I run train_ssd.py ,I found that must provide the checkpoint_path,the path to a checkpoint from which to fine-tune,and put the pre-trained VGG-16 model in it. my question is pre-trained VGG-16 is not sutable for my dataset. How to solve it?

**Comment by moonyoung430** [comment]
@HiKapok

**Comment by HiKapok** [comment]
@moonyoung430 set [scafford ](https://github.com/HiKapok/SSD.TensorFlow/blob/dd910d6643556bc236113f99d116e61c083b8b30/train_ssd.py#L403) to None if you don't want use a pretained weights
