### ISSUE TITLE
When I start train_ssd.py, No logs print after 'Done running local_init_op'

### ISSUE THREAD

**Issue by Shun14** [HiKapok/SSD.TensorFlow#13]
as title ,I met the issue like it.No information of step and all CPU core is running,what can I do? Thank you!
Tensorflow-gpu==1.6.0 and gpu memory 12GB
![image](https://user-images.githubusercontent.com/16732362/41189072-dc8998ec-6bfa-11e8-9f2e-d4454840dc8d.png)

**Comment by HiKapok** [comment]
@Shun14 maybe you are runing all computation on CPUs, so it was to slow to print the first log

**Comment by Shun14** [comment]
@HiKapok but the num_cpu_threads=0 and the gpu is using... how can I control it.I am a beginner...

**Comment by HiKapok** [comment]
@Shun14 did you set CUDA_VISIBLE_DEVICES?

**Comment by Shun14** [comment]
@HiKapok  Thank you for your quick answer.but the num_gpu=1.I have printed it

**Comment by HiKapok** [comment]
@Shun14 which version of tensorflow did you installed, you must ensure you have isntalled tensorflow-gpu, not tensorflow!

**Comment by Shun14** [comment]
@HiKapok  Yes, I installed gpu version with 1.6.0 or 1.8.0 with conda.Let's me try it.When I run the code, nvidia-smi shows the program is running.

**Comment by Shun14** [comment]
I have ran the code for two days but there was no new log showed up.So I reopened the issue.I tried on Ubuntu14.04 and 16.04 with your requirement.
tensorflow-gpu=1.6.0 
cuda=8.0
python3.5

**Comment by Shun14** [comment]
@HiKapok can you give me your wechat or email to contact ?

**Comment by HiKapok** [comment]
check your gpu utilization rate

**Comment by Jiyugaoka** [comment]
@Shun14 I run the program as described with Ubuntu16.04, CUDA9.0, CuDNN7.0, TF-GPU-1.6.0, Python3.5, and finally got the result correctly. Maybe you should read the readme.md carefully again.

**Comment by Jiyugaoka** [comment]
@HiKapok Hello, Thank you for pulling the SSD300 as a open source. I want to know when will we see the other models, such as SSD500 or a more efficient model MobileNet + SSD.

**Comment by Shun14** [comment]
![image](https://user-images.githubusercontent.com/16732362/41208455-3fb340ba-6d56-11e8-9a01-e67006e89e41.png)
gpu utilization rate like this.maybe is zero

**Comment by Shun14** [comment]
@HiKapok I'll check again.Thank you!

**Comment by HiKapok** [comment]
@Shun14 GPU wasn't used

**Comment by Shun14** [comment]
@HiKapok I modified the code 'with tf.device('/cpu:0')' to '/gpu:0' in train_ssd.py and solved the issue.Thank you very much for your reply and patience.

**Comment by HiKapok** [comment]
@Jiyugaoka I have been busy in preparing job interview this summer recently, and the plan might be delayed

**Comment by Jiyugaoka** [comment]
@HiKapok Thank you anyway, May you have a good job. Now I am preparing my final exams, when I have time I think I will do this on my own, and then we can make more connections.

**Comment by HiKapok** [comment]
@Jiyugaoka thank you

**Comment by ErrEss** [comment]
> @Shun14 maybe you are runing all computation on CPUs, so it was to slow to print the first log

This case applies to me since I'm running all computations on CPUs, is there a way to resolve this, should I convert my numpy arrays to tfrecords?
