### ISSUE TITLE
training time and hardware configuration

### ISSUE THREAD

**Issue by codegaj** [HiKapok/SSD.TensorFlow#2]
thank you for your codes,  could you give the training time and your machine hardware configuration? I am also training a ssd300 net on my own dataset, but I found  the training process is very slow, so I want to know your training time for 60k steps on pascal voc datasets, that is useful for me, maybe. Thank you!

**Comment by HiKapok** [comment]
Hi, I use batch size of 32 on single GTX 1080Ti, the image size is 300*300, it took me ~1s for each step which includes both forward and backward. Hope helpful.

**Comment by codegaj** [comment]
Thank you! that is useful. Can I add your WeChat?  I am also a master degree candidate from Hunan University.

**Comment by HiKapok** [comment]
@codegaj sure thing. Looking forward to learn together. Here is my wechat Id TCMangost
