### ISSUE TITLE
Portability for custom dataset

### ISSUE THREAD

**Issue by yjy20170** [HiKapok/SSD.TensorFlow#25]
Hi! I have a dataset of only one class object. I attempted to use balancap's SSD-Tensorflow but meet a unsolvable trouble, so I have to look for a substitute. Is it easy to change your code for my dataset? What should I notice? Thanks in advance!

**Comment by HiKapok** [comment]
@yjy20170 This repo was created with portability in my heart. You can either convert the annotations of your dataset to VOC format, or you can modify [convert_tfrecords.py](https://github.com/HiKapok/SSD.TensorFlow/blob/master/dataset/convert_tfrecords.py) to adapt to your own format and then modidy the labels in [dataset_common.py](https://github.com/HiKapok/SSD.TensorFlow/blob/master/dataset/dataset_common.py). It quite easy to adapt to your own dataset, read the codes in the above two files.

**Comment by yjy20170** [comment]
@HiKapok  Yes I have modified convert_tfrecords.py, then I just need to create a dict in "dataset_common.py" likes VOC_LABELS and change 'num_classes' in each file before training?(I can't run codes until tomorrow, so the questions might be naive.)

**Comment by yjy20170** [comment]
no problem yet, I'm preparing to prevent problems, cause I can't connect my server now and tomorrow I won't have sufficient time...Thanks very much( and maybe see you tomorrow ^^
