### ISSUE TITLE
关于改变anchor个数的问题

### ISSUE THREAD

**Issue by kunuang** [HiKapok/SSD.TensorFlow#28]
你好，我想改变一下anchor的个数，比如增加更多的长宽比，请问我应该修改哪些地方呢？谢谢作者！

**Comment by HiKapok** [comment]
@kunuang see [here](https://github.com/HiKapok/SSD.TensorFlow/blob/544e48b250129e26509560bc9d2666e3efbc199e/train_ssd.py#L169). One tuple for each layer. Both train and val codes need modified.
