### ISSUE TITLE
How do I debug the middle tensor by using tf.estimator?

### ISSUE THREAD

**Issue by xtanitfy** [HiKapok/SSD.TensorFlow#30]
In ordinary model，I can use the function of sess.run to get the tensors' running value,but how can use tf.estimator to achieve the same goal.Looking forward to your reply，thanks！

**Comment by HiKapok** [comment]
@xtanitfy It's quite easy to debug or view the contents of some tensors by tensorflow, e.g. tf.Print, tf.Debug, or you can use tf.py_func to wrap any function in python with anything you can do.

**Comment by xtanitfy** [comment]
Thank you very much!
But with the callback of tf.estimator, what time do I print by using  tf.Print or  tf.Debug?

**Comment by HiKapok** [comment]
@xtanitfy there is no necessary to use callback, you can place tf.Print anywhere in you codes

**Comment by xtanitfy** [comment]
I think i can use   tf.py_func to dispose of any tensor。Thanks！

**Comment by xtanitfy** [comment]
def my_function(array1, array2):
    return array1 + array2, array1 - array2, array1 * array2, np.dot(array1, array2)

def debug_value(array,name):
    with open(name+'.txt','w') as f:
        f.write(str(array))
    return array
    
if __name__ == '__main__':
    array1 = np.array([[1, 2], [3, 4]])
    array2 = np.array([[5, 6], [7, 8]])

    a1 = tf.placeholder(dtype=tf.float32, shape=[2, 2], name='array1')
    a2 = tf.placeholder(dtype=tf.float32, shape=[2, 2], name='array2')
    b1 = a1 * 2
    
    b1 = tf.py_func(debug_value,[b1,'b1'],[tf.float32])
    y1, y2, y3, y4 = tf.py_func(my_function, [b1, a2], [tf.float32, tf.float32, tf.float32, tf.float32])
        
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        _y1, _y2, _y3, _y4 = sess.run([y1, y2, y3, y4], feed_dict={a1: array1, a2: array2})
        print(_y1)
        print('*' * 8)
        print(_y2)
        print('*' * 8)
        print(_y3)
        print('*' * 8)
        print(_y4)

**Comment by xtanitfy** [comment]
def my_function(array1, array2):
    return array1 + array2, array1 - array2, array1 * array2, np.dot(array1, array2)

def debug_value(array,name):
    with open(name+'.txt','w') as f:
        f.write(str(array))
    return array
    
if __name__ == '__main__':
    array1 = np.array([[1, 2], [3, 4]])
    array2 = np.array([[5, 6], [7, 8]])

    a1 = tf.placeholder(dtype=tf.float32, shape=[2, 2], name='array1')
    a2 = tf.placeholder(dtype=tf.float32, shape=[2, 2], name='array2')
    b1 = a1 * 2
    
    b1 = tf.py_func(debug_value,[b1,'b1'],[tf.float32])
    y1, y2, y3, y4 = tf.py_func(my_function, [b1, a2], [tf.float32, tf.float32, tf.float32, tf.float32])
        
    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        _y1, _y2, _y3, _y4 = sess.run([y1, y2, y3, y4], feed_dict={a1: array1, a2: array2})
        print(_y1)
        print('*' * 8)
        print(_y2)
        print('*' * 8)
        print(_y3)
        print('*' * 8)
        print(_y4)

**Comment by xtanitfy** [comment]
I use this way to debug the value.
