### ISSUE TITLE
Some Debug Slove and Suggestions

### ISSUE THREAD

**Issue by SmallMunich** [HiKapok/SSD.TensorFlow#32]
the convert_tfrecords.py: row 216 

anna_file = os.path.join(directory, cur_record[0], 'Annotations', cur_record[1].replace('jpg', 'xml'))

Suggestion as followed:
anna_file = os.path.join(directory, cur_record[0], 'Annotations', cur_record[1].replace('.jpg', '.xml'))

because the file name contain the substring 'jpg' maybe replace not only the last substring.

**Comment by HiKapok** [comment]
@SmallMunich you are right, thanks for your suggestion
