### ISSUE TITLE
How can I get the recall rate ?

### ISSUE THREAD

**Issue by muomi** [HiKapok/SSD.TensorFlow#33]
Hi writer, your job is wonderful ,but how can I get the recall rate in test?Thank you for your answer！

**Comment by HiKapok** [comment]
@muomi print out the last element of 'rec' in this [line](https://github.com/HiKapok/SSD.TensorFlow/blob/2d8b0cb9b2e70281bf9dce438ff17ffa5e59075c/voc_eval.py#L255)
