### ISSUE TITLE
How  you create the anchor?

### ISSUE THREAD

**Issue by muomi** [HiKapok/SSD.TensorFlow#35]
Hi,writer !I have some problem on your code about how to create anchors.I read your code but I found that the the return of function **get_layer_anchors** are

tf.expand_dims(y_on_image,** axis=-1), tf.expand_dims(x_on_image, axis=-1), \
tf.constant(list_h_on_image, dtype=tf.float32), \
tf.constant(list_w_on_image, dtype=tf.float32), 
num_anchors_along_depth,
 num_anchors_along_spatial

but the shape of  **_list_h_on_image_**  in the first feature layer  is ###  4,while the ### shape of the **y_on_image** is ### 1440(38*38) how they combine with each other? I cannot find the code.

**Comment by HiKapok** [comment]
@muomi you should read more about broadcast in numpy or tensorflow
