### ISSUE TITLE
程序卡住但是也没有报错

### ISSUE THREAD

**Issue by SmallMunich** [HiKapok/SSD.TensorFlow#36]
Hi @HiKapok :

我在使用你的SSD算法应用时候，运行Pascal VOC数据正常！程序可以完美的跑起来，但是当我运行自己的数据集时候，程序卡住同时也不报错！想请教一下，这部分该如何在程序中定位？  ps: 数据通过VoC格式已经成功转换为tf格式，没有报错！

数据集内容：其中有部分没有目标bbox坐标信息，只有基本的长宽高！

**Comment by HiKapok** [comment]
@SmallMunich 处理一下这种没有bbox的，比如给一个标签，最后在may_batch中过滤。可以先运行prepcocessing_unittest.py定位问题

**Comment by HiKapok** [comment]
@yueweiyang you should ensure there are at least one bbox in each image after you resample them with a propability of 50%
