### ISSUE TITLE
I do not understand the sample_patch on your code

### ISSUE THREAD

**Issue by muomi** [HiKapok/SSD.TensorFlow#38]
作者你好，我没有很能看懂您代码中数据预处理的随机裁剪部分，请问对一张图片随机裁剪的时候，min_iou 是每次从 ratio_list 中等概率随机得到吗？这是不是意味着极端情况如果我将ratio_list变成[0.1, 0.1, 0.1, 0.1, 0.1, 1.]的话，随机裁剪出的iou>0.1的框是最多的？
还有，ratio_list[-0.1,0.1, 0.3, 0.5, 0.7, 0.9, 1.]有-0.1是为了随机裁剪出只有背景的图片吗？
期待您的解答～

**Comment by HiKapok** [comment]
@muomi -0.1指的是没有限制，可以去参考caffe的官方实现代码

**Comment by muomi** [comment]
嗯嗯，谢谢解答，那么min_iou是随机从radio_list等概率的到的吗？
