### ISSUE TITLE
prediction_hooks argument for tf.estimator.EstimatorSpec

### ISSUE THREAD

**Issue by netanel-s** [HiKapok/SSD.TensorFlow#4]
When trying to run eval_ssd.py I get the following error:
File "eval_ssd.py", line 373, in ssd_model_fn
    loss=None, train_op=None)
TypeError: __new__() got an unexpected keyword argument 'prediction_hooks'

I'm using TF 1.4.1. Is this another TF compatibility issue? 
Is there an easy patch I can use as you did for tf_replicate_model_fn?

Thanks in advance!

**Comment by HiKapok** [comment]
@netanel-s  Hi, sorry for that. This is indeed another compatibility issue,  you can just remove that 'prediction_hooks' argument.

**Comment by netanel-s** [comment]
Thanks.
