### ISSUE TITLE
VGG16 Pre-trained weights

### ISSUE THREAD

**Issue by kurnianggoro** [HiKapok/SSD.TensorFlow#40]
Hi, i am curious how did you make the VGG pre-trained weight as it seems different with the default weight provided in tensorflow (tf.slim). Did you apply subsampling for FC6 and FC7? Or did you convert the weights from the caffe model? Thanks in advance.

**Comment by HiKapok** [comment]
@kurnianggoro the model is converted from pytorch, which is converted from caffe, the layer of FC is sub-sampled from original caffe vgg16
