### ISSUE TITLE
how to find the output_node_names ?

### ISSUE THREAD

**Issue by SmallMunich** [HiKapok/SSD.TensorFlow#41]
你好！@HiKapok: 向你请教一个问题：
       使用你的SSD代码训练完成后，现在需要将其ckpt转换为pb形式，需要output_node_names  但是我发现ssd模型训练的输出好像是
            all_labels = tf.concat(labels_list, axis=0)
            all_scores = tf.concat(scores_list, axis=0)
            all_bboxes = tf.concat(bboxes_list, axis=0)   
多个输出，但是，我没办法看到网络Graph的最终输出节点？可以帮忙解答下当前网络的output_node_names是什么吗？ 十分感谢

**Comment by HiKapok** [comment]
@SmallMunich every node has its name, just print them out

**Comment by baoqian426** [comment]
> 你好！@HiKapok: 向你请教一个问题：
> 使用你的SSD代码训练完成后，现在需要将其ckpt转换为pb形式，需要output_node_names 但是我发现ssd模型训练的输出好像是
> all_labels = tf.concat(labels_list, axis=0)
> all_scores = tf.concat(scores_list, axis=0)
> all_bboxes = tf.concat(bboxes_list, axis=0)
> 多个输出，但是，我没办法看到网络Graph的最终输出节点？可以帮忙解答下当前网络的output_node_names是什么吗？ 十分感谢

请问怎么解决的

**Comment by SmallMunich** [comment]
@baoqian426 output_node_name 就是all_labels, all_scores, all_bboxes，你可以打印出节点来看！

**Comment by baoqian426** [comment]
> @baoqian426 output_node_name 就是all_labels, all_scores, all_bboxes，你可以打印出节点来看！

请问可不可以把你的CKPT转PB的python脚本给我发一下，还有调用PB模型预测的脚本也分享一下，如果可以真是帮大忙了，我的邮箱是1354987947@qq.com，万分谢谢你也可以加我，拜托。

**Comment by feifeiwei** [comment]
@SmallMunich  请问你转了pb吗？  有的话发我一份代码  602361419@qq.com  谢谢

**Comment by SmallMunich** [comment]
> @SmallMunich 请问你转了pb吗？ 有的话发我一份代码 [602361419@qq.com](mailto:602361419@qq.com) 谢谢

这个是我很久之前导出的，官方会有直接的导出pb，只需要确认好输入、输出节点就好了。如果代码没有改动的话，输出节点就是之前我打印的那个。你可以加载网络打印节点进行查看。

**Comment by feifeiwei** [comment]
@SmallMunich 
打印节点的脚本可以发我一份吗  602361419@qq.com 谢谢
