### ISSUE TITLE
update pipeline using MirroredStrategy

### ISSUE THREAD

**Issue by ywang-purdue** [HiKapok/SSD.TensorFlow#43]
Hi Changan,
Do you have any experience with tf.contrib.distribute.MirroredStrategy? As TF is going to depreciate replicate_model_fn, I was trying to update your code with MirroredStrategy, but I always got "ValueError: destinations must be one of a `DistributedValues` object, a device string, a list of device strings or None".

Please take a look when you have time.
Thanks,
Yu

**Comment by HiKapok** [comment]
@ywang-purdue I'm sorry, I didn't try tf.contrib.distribute.MirroredStrategy yet. And contributions is welcomed.
