### ISSUE TITLE
anchor_allowed_borders, what is it for?

### ISSUE THREAD

**Issue by SupetZYK** [HiKapok/SSD.TensorFlow#44]
I donnot understand what the 'anchor_allowed_borders' is for in function 'encode_all_labels'

```
inside_mask = tf.logical_and(tf.logical_and(anchors_ymin > -anchor_allowed_borders * 1.,
                                                        anchors_xmin > -anchor_allowed_borders * 1.),
                                        tf.logical_and(anchors_ymax < (1. + anchor_allowed_borders * 1.),
                                                        anchors_xmax < (1. + anchor_allowed_borders * 1.)))
```

I read your code that 'anchor_allowed_borders ' is all 1.0, so will the mask always be true?  (as the anchors_ymin, anchors_ymax, anchors_xmin, anchors_ymax are always between 0.0 and 1.0

**Comment by HiKapok** [comment]
@SupetZYK or you can set anchor_allowed_borders  to 8/300 to not use all anchors but those anchors inside the image border with margin 8
