### ISSUE TITLE
Should "layer_steps" change with the size of input?

### ISSUE THREAD

**Issue by ZhenyF** [HiKapok/SSD.TensorFlow#46]
Hi, I have a question of evaluation the ssd300 using different size of images

The layer_steps=[8, 16, 32, 64, 100, 300] 
and the layers_shapes = [(38, 38), (19, 19), (10, 10), (5, 5), (3, 3), (1, 1)],
 when using the input size 300. 
When I evaluate a new image with size 512, the layers_shapes will be 
[(64, 64), (32,32), (16, 16), (8, 8), (6, 6), (4, 4)]. Should the "layer_steps" be [8, 16, 32, 64, 85.3, 128]?

**Comment by HiKapok** [comment]
@ZhenyF layer_steps is same for any size of input, while the feat_shape is fixed when given the the input shape

**Comment by ZhenyF** [comment]
Many thanks for  the reply!
I can understand that the "layers_shapes" is changed with the input size but why the "layers_steps" is fixed for any input size?

**Comment by HiKapok** [comment]
@ZhenyF is is determined by the downsampled strides compared to input image

**Comment by ZhenyF** [comment]
For the last two of feature layers, feature map is reduced using "VALID" padding with stride = 1. When the input is 300, the sizes of the last two feature map will be (3,3) and (1,1), so the layer steps are 300/3=100 and 300/1 = 300 respectively.
However, when the input size is 512, the sizes of the last two feature map will be (6,6) and (4,4), so why the layer steps are not changed rather than 512/6=85.3 and 512/4 = 128 respectively?

**Comment by HiKapok** [comment]
@ZhenyF [R-CNN minus R](https://arxiv.org/abs/1506.06981)

**Comment by jamiechoi1995** [comment]
@ZhenyF check https://github.com/HiKapok/SSD.TensorFlow/pull/113/commits/1f4fc8a36beeb936cea462b1b151666ad851f75a

**Comment by renato-rodrig** [comment]
@jamiechoi1995 and image size 256?
