### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by woshilicong33** [HiKapok/SSD.TensorFlow#48]
抱歉，我想请问一下，我不用预训练参数可以吗，因为我前面的模型改了，预训练参数对不上，我想自己训练

**Comment by HiKapok** [comment]
@woshilicong33 如果不能用预训练参数，那最好把改了之后的模型先在ImageNet上预训练，然后再拿过来用

**Comment by woshilicong33** [comment]
可以在你这个程序上训练吗，我用你的程序就一定要有预训练模型才行
