### ISSUE TITLE
Incompatibility of image_ids' values and class_recs' keys in voc_eval.py

### ISSUE THREAD

**Issue by netanel-s** [HiKapok/SSD.TensorFlow#5]
image_ids' values are in the format '0.xxx', while class_recs' keys are in the format 'xxxxxxx', so line 22:
R = class_recs[image_ids[d]]
gives a KeyError.

**Comment by HiKapok** [comment]
@netanel-s  the filename [here](https://github.com/HiKapok/SSD.TensorFlow/blob/86e3fa600d8d07122e9366ae664dea8c3c87c622/eval_ssd.py#L434) should like this: b'000703.jpg', so when we write them into the result_*.txt they should be a string of six characters, see from [here](https://github.com/HiKapok/SSD.TensorFlow/blob/86e3fa600d8d07122e9366ae664dea8c3c87c622/eval_ssd.py#L449). And all the image name in 'ImageSets/Main/test.txt' are also in this format, there should be no problem when access ground truth from class_recs. BTW, did you use python3?

**Comment by netanel-s** [comment]
Sorry, my mistake, I used to conversion to TF-records of https://github.com/balancap/SSD-Tensorflow instead of the one you provided.
The output results files of eval_ssd were pretty similar to the expected ones except for the filename, so when voc_eval tried to read it, it read the score ('0.xxx') instead of filename.
Thanks and sorry for the trouble!
