### ISSUE TITLE
咋总没呢。

### ISSUE THREAD

**Issue by woshilicong33** [HiKapok/SSD.TensorFlow#50]
预训练模型。

**Comment by woshilicong33** [comment]
麻烦指点一下呗，

**Comment by woshilicong33** [comment]
你说可以，我就再改一改看看，你要说不可以，我就看看别的，就这么简单个问题

**Comment by HiKapok** [comment]
@woshilicong33 可以

**Comment by woshilicong33** [comment]
那您能稍微给点提示吗？

**Comment by woshilicong33** [comment]
我自己的参数Key mobileNet_224/conv_1/batch_norm/beta not found in checkpoint就是找不到
