### ISSUE TITLE
训练自己的数据集，一定步数后没有打印信息，也没有报错和终止

### ISSUE THREAD

**Issue by kingyj7** [HiKapok/SSD.TensorFlow#51]
您好，能帮我看看这个问题吗，我用1100张图片训练5类时停在1500步，3类时，停在了100步
...![image](https://user-images.githubusercontent.com/30548640/46005818-b49e0280-c0e8-11e8-8424-c4a435211897.png)

**Comment by HiKapok** [comment]
@kingyj7 检查一下你的数据集，确保所有图片都至少有一个框

**Comment by kingyj7** [comment]
按照您说的检查了一遍确实有这个问题，非常感谢~
    不过如果数据量大的话，类似问题我认为交给程序去检查比较好；我是在dataset/convert_tfrecords.py的`_process_image_files_batch()`方法中的` example = _convert_to_example(...)`前面加了一句`if len(bboxes)!=0:`来避免处理没有框的样本的~

**Comment by HiKapok** [comment]
哦
