### ISSUE TITLE
why the checkpoint miss?

### ISSUE THREAD

**Issue by muomi** [HiKapok/SSD.TensorFlow#54]
Hi writer！I change the conv8 in ssd_net（ i add a 3*3 conv layer in conv8 block）.when i train the new net,the code give a warning say that checkpoint miss the   weight and bais about the new layer. can i train the new net and save the checkpoint which have the new layer？thank you a lot for your help !

**Comment by HiKapok** [comment]
@muomi [](https://github.com/HiKapok/SSD.TensorFlow/blob/2d8b0cb9b2e70281bf9dce438ff17ffa5e59075c/train_ssd.py#L115)

**Comment by muomi** [comment]
Thanks for your help !I also have a problem,if i do not change the code and train as usual,whether the checkpoint save the parameters of the new layers?

**Comment by HiKapok** [comment]
@muomi yes, the codes save all savable objects by default
