### ISSUE TITLE
How to do batch test?

### ISSUE THREAD

**Issue by shenshenzhanzhan** [HiKapok/SSD.TensorFlow#63]
Thanks for your great job !!!
I want to do batch test by using tf.placeholder(batch_size,None,None,3) , but how to modify your simple_ssd_demo.py file to make the code run, hope you give me some advice, thanks.

**Comment by HiKapok** [comment]
@shenshenzhanzhan single batch size is recommended for testing

**Comment by shenshenzhanzhan** [comment]
Hi, @HiKapok . If i want to do more than single , how can i do that?

**Comment by HiKapok** [comment]
@shenshenzhanzhan then you need wrap [parse_by_class](https://github.com/HiKapok/SSD.TensorFlow/blob/2d8b0cb9b2e70281bf9dce438ff17ffa5e59075c/simple_ssd_demo.py#L190) by tf.map_fn

**Comment by shenshenzhanzhan** [comment]
@HiKapok thanks! I will try.

**Comment by jamiechoi1995** [comment]
I think anchor_encoder_decoder.decode_all_anchors may also be modified

**Comment by jamiechoi1995** [comment]
> 
> 
> @shenshenzhanzhan then you need wrap [parse_by_class](https://github.com/HiKapok/SSD.TensorFlow/blob/2d8b0cb9b2e70281bf9dce438ff17ffa5e59075c/simple_ssd_demo.py#L190) by tf.map_fn

@HiKapok parse_by_class returns data type dict, eg: (I have 3 class in my dataset)
{1: <tf.Tensor 'map_1/while/select_bboxes/nms_bboxes_1/Gather_1:0' shape=(?, 4) dtype=float32>, 2: <tf.Tensor 'map_1/while/select_bboxes/nms_bboxes_2/Gather_1:0' shape=(?, 4) d
type=float32>}, {1: <tf.Tensor 'map_1/while/select_bboxes/nms_bboxes_1/Gather:0' shape=(?,) dtype=float32>, 2: <tf.Tensor 'map_1/while/select_bboxes/nms_bboxes_2/Gather:0' shape=(?,) dtype=float32>}
How can I handle this dtype in tf.map_fn? 
Thanks.
