### ISSUE TITLE
Can you share the matching strategy with me? I am still confused about the matching strategy...

### ISSUE THREAD

**Issue by moooood** [HiKapok/SSD.TensorFlow#67]

**Comment by HiKapok** [comment]
@moooood 1. match every anchor to the max-overlaped ground truth bbox, if the max overlap iou is greater than pos_thres then assign the target from that gt, if lower than neg_thres then the anchor will be negtive sample, others anchor whose max-iou is between neg_thres and pos_thres will be ignored 2. match each gt to the max overlaped anchor, this step may override the match result of step 1.
