### ISSUE TITLE
error in ssd_net.py: module 'tensorflow.python.layers.layers' has no attribute 'Layer'

### ISSUE THREAD

**Issue by fbiying87** [HiKapok/SSD.TensorFlow#68]
I have tensorflow-gpu 1.10.1
python 3.6

Can you please help me figure out the problem? I have got the Tf-records generated. But by performing train and demo script, the above error occurred. 

Thanks a lot!

**Comment by HiKapok** [comment]
@fbiying87 the base class of tensorflow layers has been replaced with tf.keras.layer in the latest version, you should replace the base class in ssd_net.py by yourself
