### ISSUE TITLE
还是关于生成框和真实框匹配的问题。。

### ISSUE THREAD

**Issue by moooood** [HiKapok/SSD.TensorFlow#69]
在生成框和真实框匹配的过程中，是每一层，比如说conv4这一层，必须要保证每一层都有生成框跟所有真实框配对。还是说对所有层的所有生成框而言，为了保证每个真实框都有生成框与之配对，取与每个真实框iou最大的那个生成框与之配对即可？

**Comment by HiKapok** [comment]
@moooood 后者
