### ISSUE TITLE
关于小物体无法识别的问题？

### ISSUE THREAD

**Issue by moooood** [HiKapok/SSD.TensorFlow#72]
original SSD似乎一直存在对小尺寸的物体识别不太好的表现。我们组这边主要是做OCR，是被文字的，参考了你们华科白翔老师组的TextBoxes（也是基于SSD做的改进），我们这边尝试复现。但是现在的结果是对小一点的文字识别效果不太好，查准率比较低。我们排除了一系列问题，最后尝试是不是我们SSD框架写的就有问题，所以就来尝试一下你的这个版本的实现。首先确保SSD的实现没有问题，再从你的这个版本出发，改进成为TextBoxes。虽然TextBoxes已经开源，但是倔强的我们还是想自己复现一下！

**Comment by HiKapok** [comment]
@moooood 我这个没问题，推荐使用新分支[AbsoluteCoord](https://github.com/HiKapok/SSD.TensorFlow/tree/AbsoluteCoord)

**Comment by moooood** [comment]
还有一个tensorflow的代码 要怎么调试才好呢  跟一般的代码好像还不一样 调试的过程中只能看到Tensor的name, shape等等。看不到具体的值。有没有比较好的调试方式可以推荐一下呢。

**Comment by shenshenzhanzhan** [comment]
@moooood 一开始我的小物体也无法识别，后面把阈值降低发现好多小物体可以识别，只是得分比较低而已，你也可以尝试把'select_threshold'阈值降低到0.2（或者更低）。
