### ISSUE TITLE
同学 关于在VOC2007上的表现结果

### ISSUE THREAD

**Issue by moooood** [HiKapok/SSD.TensorFlow#75]
为何我使用了absolute coordinate的版本代码训练出来的模型 最后的map只有69.87%。。12万次的迭代。默认的设置我都没有去改动

**Comment by HiKapok** [comment]
@moooood 训练集VOC 07 + 12

**Comment by moooood** [comment]
...就是说是在07+12上面训练的模型，然后在07的test上面预测的结果map是77.9%是吗

**Comment by HiKapok** [comment]
caffe ssd就是这么做的

**Comment by moooood** [comment]
话说 同学 你这个版本 为啥比官方caffe版本的精度高这么多- -。
