### ISSUE TITLE
How to calculate extra_anchor_scales？

### ISSUE THREAD

**Issue by qq249356520** [HiKapok/SSD.TensorFlow#79]
extra_anchor_scales = [(0.1414,), (0.2739,), (0.4541,), (0.6315,), (0.8078,), (0.9836,)]
I want to know how to calculate  extra_anchor_scales ?  Why use this parameter? Thanks 
You can answer by Chinese

**Comment by HiKapok** [comment]
@qq249356520 see page 6 of this [paper](https://arxiv.org/pdf/1512.02325.pdf)
