### ISSUE TITLE
why is the detection performance of mAP better than the original paper's norm?

### ISSUE THREAD

**Issue by davinca** [HiKapok/SSD.TensorFlow#8]
your code is very elegant and readable! Following your instruction, I train the
ssd300 model on VOC07+12 dataset,but the mAP on VOC07 test is only **76.0%**.

I wonder that you achieve the state of the art performance(**77.8%**),even better than original paper's norm(**77.2%**). Did you do extra improvement?

**Comment by HiKapok** [comment]
@davinca how many steps did you train your SSD? You can test using my uploaded model on GoogleDrive and it will give you 77.8mAP without any cheating. BTW, did you use the latest codes?

**Comment by davinca** [comment]
Thanks a lot! =-= I didn't use the latest codes. 
I have trained the model about 120k steps. Now I try to continue to train it based on before model.
