### ISSUE TITLE
关于训练step

### ISSUE THREAD

**Issue by moondaiy** [HiKapok/SSD.TensorFlow#82]
你好。
请问下，我在看你的readme中说 重新训练(在07 + 12数据集上) 需要 ~120k steps in total, and each step (32 samples per-batch) 请问这个120K 是需要加载预训练模型么？ 
另外请问下作者，是否尝试过不使用预训练模型 进行重头的训练？

**Comment by HiKapok** [comment]
@moondaiy 是要加载预训练模型，VOC数据少从头训练必定精度不够

**Comment by LeoWang** [comment]
I hava tried to re-train the vgg16-ssd300 without restore any model weights. At the last 120k steps, it is 67% mAP.
