### ISSUE TITLE
GPU usage are zero when training with 4 GPUs

### ISSUE THREAD

**Issue by cindyasucu** [HiKapok/SSD.TensorFlow#84]
Hi @HiKapok ,
I followed your instructions in the READMe.md and converted the VOC data into tfrecords, then I started training with the VOC data by fining tuning on your pre-trained vgg16_reducedfc checkpoint model, I placed those model files onto ./model folder. But after running "python train_ssd.py", after printing out "INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op."
there is no further log any more, and I checked the GPU usage with "watch -n .5 nvidia-smi", and found that the GPU usage is always 0. I have attached the full log produced by "python train_ssd.py &> log.txt".
My system configuration is as follows:
- Ubuntu 16.04
- Python 2.7
- TensorFlow 1.8
- Training with 4 Tesla P40 GPUs
- Running training inside of Docker container
Also, I found one similar issue https://github.com/HiKapok/SSD.TensorFlow/issues/13, then I followed that solution and changed line 287 in train_ssd.py from "with tf.device('/cpu:0'):" to "with tf.device('/gpu:0'):". However, that doesn't work, the GPU usage are still zero.
I really appreciate your help! Thanks!
[log.txt](https://github.com/HiKapok/SSD.TensorFlow/files/2670971/log.txt)

**Comment by HiKapok** [comment]
@cindyasucu any problem with one GPU?

**Comment by cindyasucu** [comment]
@HiKapok Thanks for the reply. I tried to use one GPU to train, and found that actually the GPU was indeed used for training, it was just that the GPU utilization rate is so low that people can't even tell the GPU was used. Then I tried to use 4 GPUs, the story is the same: all 4 GPUs are used for training, but their utilization rate is very low, most of the time the GPUs remain idle, and only occasionally there is a 2% - 10% utilization rate showing up with nvidia-smi. Looks like most of the time is spent on CPU processing. Any insight on why the GPU utilization rate is so low? What parameters I can change to improve the GPU utilization rate? I noticed that you are using the old Queue-based input pipeline (like tf.train.batch which is going to be deprecated),  do you think this could be the reason? Maybe using TF's new tf.data for input pipeline can improve the training throughput...? Thanks a lot!

**Comment by HiKapok** [comment]
@cindyasucu no, did you try python3?

**Comment by cindyasucu** [comment]
No, let me try it then.

**Comment by rmalav15** [comment]
Same low gpu usage issue even with python3.5.
Also training seems to be stuck after few steps. I tried it multiple times with both tf1.4 and tf1.6.
Please suggest.
Thanks,

This is my current state. It's stuck here since last 2-3 hours. I am training it on a custom dataset.
![upload](https://user-images.githubusercontent.com/10210908/54187319-481a9280-44d3-11e9-8aa2-428dff162df3.png)

**Comment by HiKapok** [comment]
@rmalav15 [may be useful](https://github.com/HiKapok/SSD.TensorFlow/issues/27#issuecomment-409948751)
