### ISSUE TITLE
为什么训练模型的时候cpu占用率非常非常高？

### ISSUE THREAD

**Issue by 1453042287** [HiKapok/SSD.TensorFlow#85]
![2018-12-26 16-05-26](https://user-images.githubusercontent.com/41471119/50438266-2b38df00-0928-11e9-9105-cbd1c7394b43.png)
您好，您的这个模型训练的时候cpu占用率高达3000%多，有点吓人啊，这是正常的吗还是什么地方出了bug了？
我设置的参数是：
num_readers=2
num_preprocessing_threads=6
num_cpu_threads=0
模型是在两张titan v上训练的
能不能给点建议，多谢！

**Comment by 1453042287** [comment]
@HiKapok

**Comment by HiKapok** [comment]
@1453042287 没有问题，预处理部分确实很耗时
