### ISSUE TITLE
tf.contrib.estimator.TowerOptimizer is removed after 2018-05-31.

### ISSUE THREAD

**Issue by chuong98** [HiKapok/SSD.TensorFlow#87]
Hi, Thanks for the implementation. 
I got the error replicate_model_fn and TowerOptimizer is DEPRECATED . 
Can you help to fix these errors by tf.contrib.distribute.MirroredStrategy ?
Thanks again.

**Comment by HiKapok** [comment]
@chuong98 yes, but not now, I'm busy recently
