### ISSUE TITLE
关于hard negative mining过程的疑问，代码疑似有问题

### ISSUE THREAD

**Issue by okfang** [HiKapok/SSD.TensorFlow#92]

**Comment by HiKapok** [comment]
@okfang 没问题

**Comment by okfang** [comment]
确实， 如果按照程序配置，将neg_threshold  和 match_threshold都设置成0.5，这就不会产生ignore anchors，所以就没问题。但是如果将 neg_threshold =0.3  match_threshold=0.5 就会有问题，导致最终正负样本比例不是1:3
