### ISSUE TITLE
 Default MaxPoolingOp only supports NHWC on device type CPU

### ISSUE THREAD

**Issue by wangjing60755** [HiKapok/SSD.TensorFlow#93]
InvalidArgumentError (see above for traceback): Default MaxPoolingOp only supports NHWC on device type CPU
	 [[Node: ssd300/pool1/MaxPool = MaxPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](ssd300/conv1/conv1_2/Relu)]]

how to solve?????help!!!!!

**Comment by HiKapok** [comment]
@wangjing60755 check [this](https://github.com/HiKapok/SSD.TensorFlow/blob/b47ff6164c8925a8bbccc593719d5bbbab996058/train_ssd.py#L75)
