### ISSUE TITLE
Training stopping by itself after (250/batch_size) steps

### ISSUE THREAD

**Issue by tomrichardon** [HiKapok/SSD.TensorFlow#94]
Hello,

I'm trying to launch the training script on the pre-trained VGG-16 model that is linked in the Readme.md.
The problem that I have is that training stops by itself after (250/batch_size) steps. I didn't touch anything in the train_ssd.py script except for the batch size because my gpu was running oom with a batch_size of 32. I tried 4, 2 and 1 as batch sizes and training stopped after 62, 125 and 250 steps, saving a checkpoint. My accuracy also seems to not change at all, being at 0.750000 all the time.

My question is "What makes my training stop so quickly ?" I can't find where it comes from, although it definitely looks intentional since it stops pretty cleanly.

Here is the output of launching train_ssd.py with batch_size=2 (as you can see, it starts on step 1841 and stops by itself on step 1966) :

> (tensorflowgpu-env) C:\Users\tomri\Documents\SSD.TensorFlow-master>python train_ssd.py

WARNING:tensorflow:From train_ssd.py:427: replicate_model_fn (from tensorflow.contrib.estimator.python.estimator.replicate_model_fn) is deprecated and will be removed after 2018-05-31.
Instructions for updating:
Please use `tf.contrib.distribute.MirroredStrategy` instead.
2019-03-13 16:10:10.829767: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-03-13 16:10:12.219015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2019-03-13 16:10:12.234896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-03-13 16:10:12.683094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-13 16:10:12.686969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2019-03-13 16:10:12.689310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2019-03-13 16:10:12.692227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/device:GPU:0 with 3016 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Replicating the `model_fn` across ['/device:GPU:0'].  Variables are going to be placed on ['/device:GPU:0'].  Consolidation device is going to be /device:GPU:0.
INFO:tensorflow:Using config: {'_session_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
allow_soft_placement: true
, '_save_checkpoints_steps': None, '_evaluation_master': '', '_global_id_in_cluster': 0, '_train_distribute': None, '_task_id': 0, '_keep_checkpoint_max': 5, '_tf_random_seed': 20180503, '_service': None, '_log_step_count_steps': 10, '_num_ps_replicas': 0, '_task_type': 'worker', '_save_summary_steps': 1000, '_save_checkpoints_secs': 7200, '_is_chief': True, '_master': '', '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000025555533550>, '_keep_checkpoint_every_n_hours': 10000, '_device_fn': None, '_num_worker_replicas': 1, '_model_dir': './logs/'}
Starting a training cycle.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From C:\Users\tomri\Documents\SSD.TensorFlow-master\net\ssd_net.py:114: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From train_ssd.py:388: TowerOptimizer.__init__ (from tensorflow.contrib.estimator.python.estimator.replicate_model_fn) is deprecated and will be removed after 2018-05-31.
Instructions for updating:
Please use `tf.contrib.distribute.MirroredStrategy` instead.
INFO:tensorflow:Ignoring --checkpoint_path because a checkpoint already exists in ./logs/.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2019-03-13 16:10:25.877210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-03-13 16:10:25.882028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-13 16:10:25.886118: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2019-03-13 16:10:25.890165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2019-03-13 16:10:25.893592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3016 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from ./logs/model.ckpt-1841
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1841 into ./logs/model.ckpt.
2019-03-13 16:10:52.813970: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.57GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-13 16:10:53.824309: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.57GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
INFO:tensorflow:lr=0.001000, l2=7.292980, loc=3.477014, loss=53.604458, acc=0.750000, ce=42.834465
INFO:tensorflow:loss = 53.604458, step = 1841
INFO:tensorflow:global_step/sec: 2.24063
INFO:tensorflow:lr=0.001000, l2=7.292490, loc=3.637795, loss=25.027014, acc=0.750000, ce=14.096728
INFO:tensorflow:loss = 25.027014, step = 1851 (4.462 sec)
INFO:tensorflow:global_step/sec: 3.73853
INFO:tensorflow:lr=0.001000, l2=7.292079, loc=3.079521, loss=22.236305, acc=0.750000, ce=11.864706
INFO:tensorflow:loss = 22.236305, step = 1861 (2.676 sec)
INFO:tensorflow:global_step/sec: 3.75393
INFO:tensorflow:lr=0.001000, l2=7.291565, loc=1.217845, loss=11.967870, acc=0.750000, ce=3.458459
INFO:tensorflow:loss = 11.96787, step = 1871 (2.665 sec)
INFO:tensorflow:global_step/sec: 3.73993
INFO:tensorflow:lr=0.001000, l2=7.291090, loc=3.487017, loss=17.143929, acc=0.750000, ce=6.365822
INFO:tensorflow:loss = 17.143929, step = 1881 (2.672 sec)
INFO:tensorflow:global_step/sec: 3.66937
INFO:tensorflow:lr=0.001000, l2=7.290852, loc=3.540547, loss=32.483604, acc=0.750000, ce=21.652206
INFO:tensorflow:loss = 32.483604, step = 1891 (2.728 sec)
INFO:tensorflow:global_step/sec: 3.78508
INFO:tensorflow:lr=0.001000, l2=7.290482, loc=2.461484, loss=13.741415, acc=0.750000, ce=3.989449
INFO:tensorflow:loss = 13.741415, step = 1901 (2.640 sec)
INFO:tensorflow:global_step/sec: 3.79082
INFO:tensorflow:lr=0.001000, l2=7.290192, loc=3.321430, loss=21.725256, acc=0.750000, ce=11.113634
INFO:tensorflow:loss = 21.725256, step = 1911 (2.638 sec)
INFO:tensorflow:global_step/sec: 3.75983
INFO:tensorflow:lr=0.001000, l2=7.289964, loc=2.578511, loss=13.988897, acc=0.750000, ce=4.120422
INFO:tensorflow:loss = 13.988897, step = 1921 (2.663 sec)
INFO:tensorflow:global_step/sec: 3.76216
INFO:tensorflow:lr=0.001000, l2=7.289906, loc=5.934974, loss=40.700157, acc=0.750000, ce=27.475279
INFO:tensorflow:loss = 40.700157, step = 1931 (2.655 sec)
INFO:tensorflow:global_step/sec: 3.76096
INFO:tensorflow:lr=0.001000, l2=7.289580, loc=2.893521, loss=17.323259, acc=0.750000, ce=7.140158
INFO:tensorflow:loss = 17.32326, step = 1941 (2.659 sec)
INFO:tensorflow:global_step/sec: 3.77241
INFO:tensorflow:lr=0.001000, l2=7.289131, loc=2.843292, loss=13.380405, acc=0.750000, ce=3.247983
INFO:tensorflow:loss = 13.380405, step = 1951 (2.651 sec)
INFO:tensorflow:global_step/sec: 3.77656
INFO:tensorflow:lr=0.001000, l2=7.288894, loc=2.549889, loss=13.519226, acc=0.750000, ce=3.680444
INFO:tensorflow:loss = 13.519226, step = 1961 (2.648 sec)
INFO:tensorflow:Saving checkpoints for 1966 into ./logs/model.ckpt.
INFO:tensorflow:Loss for final step: 16.647438.

**Comment by HiKapok** [comment]
@tomrichardon did you use custom dataset?

**Comment by tomrichardon** [comment]
No, I'm working with Pascal VOC 2007+2012

**Comment by tomrichardon** [comment]
No idea then ? I'm still stuck here, it looks like the tf.train.MonitoredSession is deciding that it should stop but I have no clue as to why it would.

**Comment by HiKapok** [comment]
@tomrichardon coule you give more details about the evironment used? please delete checkpoints in loggs before you run traininig

**Comment by tomrichardon** [comment]
Sure. Here is the list of the packages installed in my working environment

> _tflow_select             2.1.0                       gpu
> absl-py                   0.4.1                    py35_0
> astor                     0.7.1                    py35_0
> backports_abc             0.5                      py35_0
> beautifulsoup4            4.6.3                    py35_0
> blas                      1.0                         mkl
> ca-certificates           2019.1.23                     0
> certifi                   2018.8.24                py35_1
> cudatoolkit               9.0                           1
> cudnn                     7.3.1                 cuda9.0_0
> cycler                    0.10.0           py35hcc71164_0
> cython                    0.28.5           py35h6538335_0
> freetype                  2.9.1                ha9979f8_1
> futures                   3.0.3                    py35_0
> gast                      0.2.0                    py35_0
> git                       2.20.1               h6bb4b03_0
> grpcio                    1.12.1           py35h1a1b453_0
> h5py                      2.8.0            py35hf7173ca_2
> hdf5                      1.8.20               hac2f561_1
> icc_rt                    2019.0.0             h0cc432a_1
> icu                       58.2                 ha66f8fd_1
> imageio                   2.4.1                    py35_0
> intel-openmp              2019.1                      144
> jpeg                      9b                   hb83a4c4_2
> keras                     2.2.2                         0
> keras-applications        1.0.4                    py35_1
> keras-base                2.2.2                    py35_0
> keras-preprocessing       1.0.2                    py35_1
> kiwisolver                1.0.1            py35h6538335_0
> libiconv                  1.15                 h1df5818_7
> libopencv                 3.4.2                h20b85fd_0
> libpng                    1.6.36               h2a8f88b_0
> libprotobuf               3.6.0                h1a1b453_0
> libtiff                   4.0.10               hb898794_2
> libxml2                   2.9.9                h464c3ec_0
> libxslt                   1.1.33               h579f668_0
> linecache2                1.0.0                    py35_0
> lxml                      4.2.5            py35hef2cd61_0
> markdown                  2.6.11                   py35_0
> matplotlib                3.0.0            py35hd159220_0
> mkl                       2018.0.3                      1
> mkl_fft                   1.0.6            py35hdbbee80_0
> mkl_random                1.0.1            py35h77b88f5_1
> numpy                     1.15.2           py35ha559c80_0
> numpy-base                1.15.2           py35h8128ebf_0
> olefile                   0.46                     py35_0
> opencv                    3.4.2            py35h40b0b35_0
> openssl                   1.1.1b               he774522_1
> pillow                    5.2.0            py35h08bbbbd_0
> pip                       10.0.1                   py35_0
> protobuf                  3.6.0            py35he025d50_0
> py-opencv                 3.4.2            py35hc319ecb_0
> pycocotools               2.0                      pypi_0    pypi
> pyparsing                 2.2.1                    py35_0
> pyqt                      5.9.2            py35h6538335_2
> pyreadline                2.1                      py35_1
> python                    3.5.6                he025d50_0
> python-dateutil           2.7.3                    py35_0
> pytz                      2018.5                   py35_0
> pyyaml                    3.13             py35hfa6e2cd_0
> qt                        5.9.7            vc14h73c81de_0
> scikit-learn              0.20.0           py35heebcf9a_1
> scipy                     1.1.0            py35h4f6bf74_1
> setuptools                40.2.0                   py35_0
> singledispatch            3.4.0.3          py35h33f66b4_0
> sip                       4.19.8           py35h6538335_0
> six                       1.11.0                   py35_1
> sqlite                    3.26.0               he774522_0
> tensorboard               1.10.0           py35he025d50_0
> tensorflow                1.10.0          gpu_py35ha5d5ef7_0
> tensorflow-base           1.10.0          gpu_py35h6e53903_0
> tensorflow-gpu            1.10.0               hf154084_0
> termcolor                 1.1.0                    py35_1
> tk                        8.6.8                hfa6e2cd_0
> tornado                   5.1.1            py35hfa6e2cd_0
> tqdm                      4.31.1                     py_0
> traceback2                1.4.0                    py35_0
> unittest2                 1.1.0                    py35_0
> vc                        14.1                 h0510ff6_4
> vs2008_runtime            9.00.30729.1         hfaea7d5_1
> vs2015_runtime            14.15.26706          h3a45250_0
> werkzeug                  0.14.1                   py35_0
> wheel                     0.31.1                   py35_0
> wincertstore              0.2              py35hfebbdb8_0
> xz                        5.2.4                h2fa13f4_4
> yaml                      0.1.7                hc54c509_2
> zlib                      1.2.11               h62dcd97_3
> zstd                      1.3.7                h508b16e_0

So mainly Tensorflow 1.10.0, cuda 9.0 and cudnn 7.3.1
My GPU is a Nvidia GeForce GTX 1050 with 4GB.


Here is the result of running training without any checkpoint (batch_size is 2):

(tensorflowgpu-env) C:\Users\tomri\Documents\SSD.TensorFlow-master>python train_ssd.py

> WARNING:tensorflow:From train_ssd.py:426: replicate_model_fn (from tensorflow.contrib.estimator.python.estimator.replicate_model_fn) is deprecated and will be removed after 2018-05-31.
> Instructions for updating:
> Please use `tf.contrib.distribute.MirroredStrategy` instead.
> 2019-03-21 12:32:05.378344: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
> 2019-03-21 12:32:07.737963: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
> name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
> pciBusID: 0000:01:00.0
> totalMemory: 4.00GiB freeMemory: 3.30GiB
> 2019-03-21 12:32:07.744357: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
> 2019-03-21 12:34:47.892072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-03-21 12:34:47.898038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
> 2019-03-21 12:34:47.899779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
> 2019-03-21 12:34:48.069223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/device:GPU:0 with 3016 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
> INFO:tensorflow:Replicating the `model_fn` across ['/device:GPU:0'].  Variables are going to be placed on ['/device:GPU:0'].  Consolidation device is going to be /device:GPU:0.
> INFO:tensorflow:Using config: {'_log_step_count_steps': 10, '_num_worker_replicas': 1, '_train_distribute': None, '_keep_checkpoint_max': 5, '_device_fn': None, '_session_config': gpu_options {
>   per_process_gpu_memory_fraction: 1.0
> }
> allow_soft_placement: true
> , '_model_dir': './logs/', '_num_ps_replicas': 0, '_task_id': 0, '_service': None, '_save_checkpoints_secs': 7200, '_evaluation_master': '', '_save_summary_steps': 1000, '_save_checkpoints_steps': None, '_task_type': 'worker', '_master': '', '_keep_checkpoint_every_n_hours': 10000, '_tf_random_seed': 20180503, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001D303823828>, '_is_chief': True, '_global_id_in_cluster': 0}
> Starting a training cycle.
> INFO:tensorflow:Calling model_fn.
> WARNING:tensorflow:From train_ssd.py:387: TowerOptimizer.__init__ (from tensorflow.contrib.estimator.python.estimator.replicate_model_fn) is deprecated and will be removed after 2018-05-31.
> Instructions for updating:
> Please use `tf.contrib.distribute.MirroredStrategy` instead.
> INFO:tensorflow:Fine-tuning from ./model/vgg_16\vgg16_reducedfc.ckpt. Ignoring missing vars: True.
> INFO:tensorflow:Done calling model_fn.
> INFO:tensorflow:Create CheckpointSaverHook.
> INFO:tensorflow:Graph was finalized.
> 2019-03-21 12:35:06.487018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
> 2019-03-21 12:35:06.493017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-03-21 12:35:06.503060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
> 2019-03-21 12:35:06.505575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
> 2019-03-21 12:35:06.507635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3016 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
> INFO:tensorflow:Running local_init_op.
> INFO:tensorflow:Done running local_init_op.
> INFO:tensorflow:Saving checkpoints for 0 into ./logs/model.ckpt.
> 2019-03-21 12:38:24.746745: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.57GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 2019-03-21 12:38:26.716749: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.57GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> INFO:tensorflow:lr=0.000100, loc=2.236585, loss=28.782213, acc=0.000000, ce=19.275513, l2=7.270115
> INFO:tensorflow:loss = 28.782213, step = 0
> INFO:tensorflow:global_step/sec: 2.22694
> INFO:tensorflow:lr=0.000100, loc=2.588176, loss=22.296719, acc=0.018519, ce=12.438429, l2=7.270113
> INFO:tensorflow:loss = 22.296719, step = 10 (4.483 sec)
> INFO:tensorflow:global_step/sec: 3.67073
> INFO:tensorflow:lr=0.000100, loc=2.446927, loss=23.534426, acc=0.013699, ce=13.817399, l2=7.270100
> INFO:tensorflow:loss = 23.534426, step = 20 (2.693 sec)
> INFO:tensorflow:global_step/sec: 3.79085
> INFO:tensorflow:lr=0.000100, loc=3.883078, loss=23.198439, acc=0.010638, ce=12.045286, l2=7.270074
> INFO:tensorflow:loss = 23.198439, step = 30 (2.638 sec)
> INFO:tensorflow:global_step/sec: 3.77797
> INFO:tensorflow:lr=0.000100, loc=2.814501, loss=22.116505, acc=0.010163, ce=12.031961, l2=7.270043
> INFO:tensorflow:loss = 22.116505, step = 40 (2.678 sec)
> INFO:tensorflow:global_step/sec: 3.72474
> INFO:tensorflow:lr=0.000100, loc=3.213393, loss=22.586256, acc=0.023952, ce=12.102850, l2=7.270012
> INFO:tensorflow:loss = 22.586256, step = 50 (2.653 sec)
> INFO:tensorflow:global_step/sec: 3.76756
> INFO:tensorflow:lr=0.000100, loc=3.436825, loss=21.489790, acc=0.073944, ce=10.782980, l2=7.269985
> INFO:tensorflow:loss = 21.48979, step = 60 (2.654 sec)
> INFO:tensorflow:global_step/sec: 3.78873
> INFO:tensorflow:lr=0.000100, loc=3.148245, loss=22.771851, acc=0.074510, ce=12.353648, l2=7.269958
> INFO:tensorflow:loss = 22.77185, step = 70 (2.639 sec)
> INFO:tensorflow:global_step/sec: 3.77893
> INFO:tensorflow:lr=0.000100, loc=2.164743, loss=21.776260, acc=0.073694, ce=12.341585, l2=7.269931
> INFO:tensorflow:loss = 21.77626, step = 80 (2.647 sec)
> INFO:tensorflow:global_step/sec: 3.7794
> INFO:tensorflow:lr=0.000100, loc=2.861221, loss=21.818876, acc=0.101415, ce=11.687750, l2=7.269905
> INFO:tensorflow:loss = 21.818876, step = 90 (2.647 sec)
> INFO:tensorflow:global_step/sec: 3.78938
> INFO:tensorflow:lr=0.000100, loc=2.791709, loss=22.201305, acc=0.101275, ce=12.139722, l2=7.269875
> INFO:tensorflow:loss = 22.201305, step = 100 (2.639 sec)
> INFO:tensorflow:global_step/sec: 3.77796
> INFO:tensorflow:lr=0.000100, loc=2.372598, loss=21.743816, acc=0.102000, ce=12.101371, l2=7.269847
> INFO:tensorflow:loss = 21.743816, step = 110 (2.646 sec)
> INFO:tensorflow:global_step/sec: 3.77358
> INFO:tensorflow:lr=0.000100, loc=2.965104, loss=21.368793, acc=0.115578, ce=11.133867, l2=7.269823
> INFO:tensorflow:loss = 21.368793, step = 120 (2.650 sec)
> INFO:tensorflow:Saving checkpoints for 125 into ./logs/model.ckpt.
> INFO:tensorflow:Loss for final step: 21.471064.

**Comment by HiKapok** [comment]
@tomrichardon did you try tensorflow 1.6?

**Comment by HiKapok** [comment]
@tomrichardon make sure tfrecords is converted correctly
