### ISSUE TITLE
why is the select_threshold  2

### ISSUE THREAD

**Issue by tutu123133** [HiKapok/SSD.TensorFlow#95]
tf.app.flags.DEFINE_float(
    'select_threshold', 0.2, 'Class-specific confidence score threshold for selecting a box.')

**Comment by HiKapok** [comment]
@tutu123133 depends on your needs

**Comment by tutu123133** [comment]
I ran https://github.com/balancap/SSD-Tensorflow code
but many goals score very low, the threshold in the code is 0.5. So that many of my goals are not detected with a threshold of 0.5. 

Is this SSD network feature relevant?

But faster rcnn is not like this. Faster rcnn scores are generally high

Do you know the reason?

Thank you for your answer! I am training your network. You are very great

**Comment by HiKapok** [comment]
@tutu123133 threshold should be set only for visulisation, not for evaluation
