### ISSUE TITLE
train_ssd Error

### ISSUE THREAD

**Issue by fuaiguo** [HiKapok/SSD.TensorFlow#98]
By the way, has this error ever been encountered"TypeError: Expected binary or unicode string, got None" thank you.

**Comment by HiKapok** [comment]
@fuaiguo please check README.MD carefully before lauch an issue

**Comment by fuaiguo** [comment]
你好，我报了这个错误，按照您的解决方案需要下载ckpt进行训练，但是由于是自己的数据集，如果想从头开始训练呢？这个错误应该怎么解决呢，谢谢 @HiKapok

**Comment by fuaiguo** [comment]
我已经能找到解决方案，不好意思，非常感谢您的代码，今后有问题再向您请教 @HiKapok

**Comment by ylqi007** [comment]
@fuaiguo 
I had the same problem.  How did you solve that problem?

**Comment by fuaiguo** [comment]
scaffold=tf.train.Scaffold(init_fn=get_init_fn()) ------- >>>>scaffold = None @ylqi007
